Db:
  Name: vocascan
  Username: postgres
  Password: postgres

Server:
  Domain: api.vocascan.test
  Config: /etc/vocascan/vocascan.config.js
  Db:
    Host: http://vocascan-db-service
    Port: 5432

Client:
  Domain: vocascan.test
  BackendUrl: https://api.vocascan.test
