apiVersion: v1
data:
  vocascan-db-pass: TElVVWQzYk9yWnRwSTZKS3RZUWpzcjhXZGFnQnlybFc=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vocascan-db-pass
  name: vocascan-db-pass
type: Opaque
